### ISSUE TITLE
Wiring for regular ESP8266

### ISSUE THREAD

**Issue by franklinvv** [rgrokett/ESP8266_PIRv2#2]
I suspect that this will only work with a ESP8266 Huzzah, right? The regular ESP8266 modules that I have all freeze when RST is held low, and come back to life again when RST rises again. With the wiring that you propose, a regular ESP8266 is disabled when motion is detected, and when it comes back to life motion is already gone because that's when the PIR outputs a low signal.

**Comment by rgrokett** [comment]
I see this in the ESP8266 info:
_**RST** - this is the reset pin for the ESP8266, pulled high by default. When pulled down to ground momentarily it will reset the ESP8266 system. This pin is 5V compliant._

The PIR normally is LOW and goes HIGH with motion. Thus the 2N2222 is used to reverse this.

RST shouldn't be held low. Only momentarily set low then back to high. Try disconnecting the 2N2222 collector from GPIO16 and RST, then use a voltmeter to verify it is default High and goes Low when PIR detects motion then back High after motion stops.  You can also verify the PIR is going High during motion and Low otherwise. If it works oppositely, then the 2N2222 would not be needed.

Note that GPIO16 is used only to make sure the RST is High when no motion.  You may not need it, as long as the 2N2222 collector reads less than 2v when PIR detects motion and greater than 3v when PIR does not detect motion.

It should be the same for regular ESP8266 modules as the Huzzah.

Hope this helps
